/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.cafe.ui.component;

import java.io.File;
import java.util.function.Consumer;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import lombok.Getter;
import lombok.Setter;
import poly.cafe.util.XIcon;

/**
 *
 * @author DELL
 */
public class ImageJPanel extends javax.swing.JPanel {
    public ImageJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        lblPicture = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 1, true));
        setLayout(new java.awt.BorderLayout());

        lblPicture.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        lblPicture.setForeground(new java.awt.Color(255, 102, 102));
        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setText("Image");
        lblPicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPictureMouseClicked(evt);
            }
        });
        add(lblPicture, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lblPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPictureMouseClicked
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = XIcon.copyTo(fileChooser.getSelectedFile(), this.folder);
            if (file != null) {
                setIcon(file.getName());
                if (fileChanged != null) {
                    fileChanged.accept(file);
                }
            }
        }
    }//GEN-LAST:event_lblPictureMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel lblPicture;
    // End of variables declaration//GEN-END:variables
    
    private String folder = "images";
    private Consumer<File> fileChanged;

    // Constructor và các method khác (initComponents...) bạn giữ nguyên hoặc thêm ở đây

    // Getter cho folder
    public String getFolder() {
        return folder;
    }

    // Setter cho folder
    public void setFolder(String folder) {
        this.folder = folder;
    }

    // Getter cho fileChanged
    public Consumer<File> getFileChanged() {
        return fileChanged;
    }

    // Setter cho fileChanged
    public void setFileChanged(Consumer<File> fileChanged) {
        this.fileChanged = fileChanged;
    }

    // Method lấy icon hiện tại (từ tooltip của lblPicture)
    public String getIcon() {
        return lblPicture.getToolTipText();
    }

    // Method set icon, hiển thị ảnh và đặt tooltip
    public void setIcon(String icon) {
        lblPicture.setText("");
        lblPicture.setToolTipText(icon);
        XIcon.setIcon(lblPicture, new File(this.folder, icon));
    }
}
