/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.ui1;

import javax.swing.ButtonGroup;
import poly.cafe.dao.impl.UserDAOImpl;
import poly.cafe.dao1.UserDAO;
import poly.cafe.entity.User;
import poly.cafe.util.Auth;
import poly.cafe.util.XDialog;

/**
 *
 * @author Hieu
 */
public class EditJDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditJDialog
     */
    public EditJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); // Đặt cửa sổ ra giữa màn hình
        userDAO = UserDAOImpl.getInstance(); // Khởi tạo DAO để tương tác với CSDL

        // Khởi tạo ButtonGroup cho các JRadioButton vai trò
        roleButtonGroup = new ButtonGroup();
        roleButtonGroup.add(rdoNhanVien);
        roleButtonGroup.add(rdoQuanLi);

        // Gắn các sự kiện cho nút (đã được gọi trong constructor)
        setupEventListeners();
    }
    private UserDAO userDAO;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Điền thông tin của người dùng hiện tại vào form.
     */
    private void loadUserInfo() {
    if (!Auth.isLogin()) {
        // Nếu chưa đăng nhập, mở LoginJDialog
        LoginJDialog login = new LoginJDialog(null, true); // Hoặc dùng SwingUtilities.getWindowAncestor(this)
        login.setVisible(true);

        // Sau khi LoginJDialog đóng, kiểm tra lại trạng thái đăng nhập
        if (!Auth.isLogin()) {
            XDialog.alert("Chưa đăng nhập. Hệ thống sẽ đóng.");
            this.dispose(); // Thoát nếu vẫn chưa đăng nhập
            return;
        }
    }

    // Nếu đã đăng nhập (hoặc đăng nhập xong)
    User currentUser = Auth.user;

    txtUsername.setText(currentUser.getUsername());
    txtName.setText(currentUser.getFullname());
    txtUsername.setEditable(false);

    if (currentUser.isManager()) {
        rdoQuanLi.setSelected(true);
    } else {
        rdoNhanVien.setSelected(true);
    }

    if (!Auth.isManager()) {
        rdoNhanVien.setEnabled(false);
        rdoQuanLi.setEnabled(false);
        jLabel3.setText("Vai trò (không thể chỉnh sửa)");
    }
}


    /**
     * Gắn các sự kiện cho các nút.
     * Phương thức này đã được gọi trong constructor.
     */
    private void setupEventListeners() {
        // Gắn listener cho btnSave
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        // Gắn listener cho btnClose
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        // Gắn listener cho sự kiện cửa sổ được mở
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
    }

    private void updateUserInfo() {
        if (Auth.isLogin()) {
            User currentUser = Auth.user; // Lấy thông tin người dùng hiện tại

            String newFullname = txtName.getText().trim();
            boolean newIsManager = rdoQuanLi.isSelected();

            // Validate dữ liệu nhập
            if (newFullname.isEmpty()) {
                XDialog.alert( "Họ và tên không được để trống!");
                return;
            }

            // Tạo một đối tượng User mới với các thông tin đã chỉnh sửa
            User updatedUser = new User();
            updatedUser.setUsername(currentUser.getUsername()); // Tên đăng nhập không đổi
            updatedUser.setPassword(currentUser.getPassword()); // Giữ nguyên mật khẩu (nếu không có trường đổi mật khẩu)
            updatedUser.setEnabled(currentUser.isEnabled());     // Giữ nguyên trạng thái hoạt động
            updatedUser.setFullname(newFullname);              // Cập nhật họ và tên
            updatedUser.setPhoto(currentUser.getPhoto());      // Giữ nguyên ảnh (nếu không có chức năng đổi ảnh)

            // Chỉ cập nhật vai trò nếu người dùng hiện tại là quản lý
            if (Auth.isManager()) {
                updatedUser.setManager(newIsManager);
            } else {
                updatedUser.setManager(currentUser.isManager()); // Giữ nguyên vai trò nếu không phải quản lý
            }

            try {
                userDAO.update(updatedUser); // Gọi DAO để cập nhật vào CSDL
                Auth.user = updatedUser;     // Cập nhật lại đối tượng người dùng trong Auth

                XDialog.alert( "Cập nhật thông tin thành công!");
                this.dispose(); // Đóng cửa sổ sau khi cập nhật thành công
            } catch (Exception e) {
                XDialog.alert( "Cập nhật thông tin thất bại: " + e.getMessage());
                e.printStackTrace(); // In lỗi ra console để debug
            }
        }
    }

    /**
     * Xử lý sự kiện khi nút "Đóng" được nhấn.
     * @param evt Sự kiện ActionEvent.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rdoNhanVien = new javax.swing.JRadioButton();
        rdoQuanLi = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Tên đăng nhập");

        jLabel2.setText("Họ và tên");

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel3.setText("Vai trò");

        rdoNhanVien.setText("Nhân viên");

        rdoQuanLi.setText("Quản lí");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoQuanLi))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                        .addComponent(txtName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNhanVien)
                    .addComponent(rdoQuanLi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        this.updateUserInfo();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.loadUserInfo();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditJDialog dialog = new EditJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoQuanLi;
    private javax.swing.ButtonGroup roleButtonGroup;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
