/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.ui1;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import poly.cafe.util.InternetChecker;

/**
 *
 * @author Hieu
 */
public class KetNoiWifiJDialog extends javax.swing.JDialog {
    private InternetChecker checker;
    private final Set<String> connectedBefore = new HashSet<>();
    public KetNoiWifiJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWifiAvailable = new javax.swing.JList<>();
        btnContinue = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("VUI LÒNG KẾT NỐI WIFI");

        listWifiAvailable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listWifiAvailableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listWifiAvailable);

        btnContinue.setText("Tiếp tục");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinue)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinue))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultListModel<String> model = new DefaultListModel<>();
    listWifiAvailable.setModel(model);

    List<String> wifiList = poly.cafe.util.InternetChecker.getAllWifiStatus();
    for (String wifi : wifiList) {
        model.addElement(wifi);
    }
    }//GEN-LAST:event_formWindowOpened

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        if (poly.cafe.util.InternetChecker.isInternetAvailable()) {
        jLabel1.setText("✅ Đã kết nối Internet. Đang tiếp tục...");

        // Dừng luồng kiểm tra khi chuyển sang cửa sổ tiếp theo
        if (checker != null) checker.stopChecking();

        try {
            Thread.sleep(1000); // Cho người dùng thấy thông báo
        } catch (InterruptedException e) {
            // Không cần xử lý gì thêm
        }

        this.dispose(); // Đóng cửa sổ này
    } else {
        jLabel1.setText("❌ Không có kết nối Internet! Vui lòng kiểm tra lại.");
    }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void listWifiAvailableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listWifiAvailableMouseClicked
        String selected = listWifiAvailable.getSelectedValue();
if (selected == null) return;

// Tách SSID bằng cách loại bỏ icon và trạng thái
String ssid = selected.replaceAll("^[✅⚠️❌ ]+", "").split(" - ")[0].trim();

// Nếu đã kết nối thì không làm gì cả
if (selected.contains("Đã kết nối")) return;

// Nếu đã từng kết nối trước đó thì thử kết nối lại không cần hỏi mật khẩu
if (connectedBefore.contains(ssid)) {
    tryConnect(ssid, null);
    return;
}

// Chưa từng kết nối, yêu cầu người dùng nhập mật khẩu
String password = poly.cafe.util.XDialog.prompt("Nhập mật khẩu cho Wi-Fi: " + ssid, "Yêu cầu mật khẩu");
if (password == null || password.trim().isEmpty()) return;

// Thử kết nối với mật khẩu đã nhập
boolean success = tryConnect(ssid, password);
if (success) {
    connectedBefore.add(ssid);
}

    }//GEN-LAST:event_listWifiAvailableMouseClicked
private boolean tryConnect(String ssid, String password) {
    try {
        // Nếu password null nghĩa là đã add profile trước đó, chỉ cần connect
        if (password == null) {
            Process connect = new ProcessBuilder("cmd.exe", "/c",
                "netsh wlan connect name=\"" + ssid + "\" ssid=\"" + ssid + "\"").start();
            connect.waitFor();
            poly.cafe.util.XDialog.alert("Đang kết nối tới: " + ssid);
            return true;
        }

        // Tạo profile Wi-Fi XML
        String profileXml =
            "<?xml version=\"1.0\"?>" +
            "<WLANProfile xmlns=\"http://www.microsoft.com/networking/WLAN/profile/v1\">" +
            "<name>" + ssid + "</name>" +
            "<SSIDConfig><SSID><name>" + ssid + "</name></SSID></SSIDConfig>" +
            "<connectionType>ESS</connectionType>" +
            "<connectionMode>auto</connectionMode>" +
            "<MSM><security><authEncryption>" +
            "<authentication>WPA2PSK</authentication>" +
            "<encryption>AES</encryption><useOneX>false</useOneX>" +
            "</authEncryption>" +
            "<sharedKey><keyType>passPhrase</keyType><protected>false</protected>" +
            "<keyMaterial>" + password + "</keyMaterial>" +
            "</sharedKey></security></MSM></WLANProfile>";

        // Ghi file XML tạm
        File temp = File.createTempFile("wifi-", ".xml");
        try (FileWriter fw = new FileWriter(temp)) {
            fw.write(profileXml);
        }

        // Thêm profile
        Process addProfile = new ProcessBuilder("cmd.exe", "/c",
            "netsh wlan add profile filename=\"" + temp.getAbsolutePath() + "\"").start();
        addProfile.waitFor();

        // Kết nối
        Process connect = new ProcessBuilder("cmd.exe", "/c",
            "netsh wlan connect name=\"" + ssid + "\" ssid=\"" + ssid + "\"").start();
        connect.waitFor();

        // Thông báo
        poly.cafe.util.XDialog.alert("Đã gửi yêu cầu kết nối tới: " + ssid);
        temp.deleteOnExit();
        return true;

    } catch (IOException | InterruptedException e) {
        e.printStackTrace();
        poly.cafe.util.XDialog.alert("Lỗi khi kết nối Wi-Fi: " + e.getMessage());
        return false;
    }
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetNoiWifiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetNoiWifiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetNoiWifiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetNoiWifiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KetNoiWifiJDialog dialog = new KetNoiWifiJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnContinue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listWifiAvailable;
    // End of variables declaration//GEN-END:variables
}
