/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui1;
import java.awt.AWTException;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Enumeration;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import poly.cafe.dao.impl.UserDAOImpl;
import poly.cafe.dao1.UserDAO;
import poly.cafe.util.InternetChecker;
import poly.cafe.util.XAuth;
import poly.cafe.util.XDialog;
import poly.cafe.util.XIcon;

/**
 *
 * @author DELL
 */
public final class PolyCafeJFrame extends javax.swing.JFrame implements PolyCafeController{
private TrayIcon trayIcon;
public PolyCafeJFrame() {
    initComponents();
    this.init();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        pnlLeftCenter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        lblFullname = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnTime = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnQuanLiDoAn = new javax.swing.JButton();
        btnKhuyenMai = new javax.swing.JButton();
        btnWifiManager = new javax.swing.JToggleButton();
        pnlLeftBottom = new javax.swing.JPanel();
        btnSales = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlManager = new javax.swing.JPanel();
        pnlCenterBottom = new javax.swing.JPanel();
        btnDrinkMgr = new javax.swing.JButton();
        btnCategoryMgr = new javax.swing.JButton();
        btnCardMgr = new javax.swing.JButton();
        btnBillMgr = new javax.swing.JButton();
        btnUserMgr = new javax.swing.JButton();
        btnReportMgr = new javax.swing.JButton();
        pnlBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Poly Cafe");
        setBackground(new java.awt.Color(255, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlLeft.setBackground(new java.awt.Color(255, 153, 102));
        pnlLeft.setLayout(new java.awt.BorderLayout(1, 1));

        pnlLeftCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeftCenter.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 0), new java.awt.Color(255, 204, 102), new java.awt.Color(51, 255, 204), new java.awt.Color(0, 255, 0)));
        jPanel1.setOpaque(false);

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/trump-small.png"))); // NOI18N
        lblPhoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        lblPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhotoMouseClicked(evt);
            }
        });

        lblFullname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(255, 51, 0));
        lblFullname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFullname.setText("Nguyễn Văn Tèo");

        btnEdit.setBackground(new java.awt.Color(102, 204, 255));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEdit.setText("CHỈNH SỬA");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTime.setBackground(new java.awt.Color(255, 204, 255));
        btnTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTime.setText("THỜI GIAN");
        btnTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(new java.awt.Color(255, 255, 102));
        btnKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKhachHang.setText("KHÁCH HÀNG");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnQuanLiDoAn.setBackground(new java.awt.Color(0, 204, 255));
        btnQuanLiDoAn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnQuanLiDoAn.setText("QUẢN LÍ ĐỒ ĂN");
        btnQuanLiDoAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLiDoAnActionPerformed(evt);
            }
        });

        btnKhuyenMai.setBackground(new java.awt.Color(153, 153, 0));
        btnKhuyenMai.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnKhuyenMai.setText("KHUYẾN MÃI");
        btnKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenMaiActionPerformed(evt);
            }
        });

        btnWifiManager.setBackground(new java.awt.Color(204, 204, 0));
        btnWifiManager.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnWifiManager.setText("Wifi");
        btnWifiManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWifiManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuanLiDoAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWifiManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFullname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTime, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(btnQuanLiDoAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnWifiManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pnlLeftCenter.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlLeft.add(pnlLeftCenter, java.awt.BorderLayout.CENTER);

        pnlLeftBottom.setBackground(new java.awt.Color(102, 255, 51));
        pnlLeftBottom.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(102, 255, 102)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 51), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 204))), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(204, 255, 51), new java.awt.Color(255, 0, 153), new java.awt.Color(255, 102, 102))));
        pnlLeftBottom.setPreferredSize(new java.awt.Dimension(310, 150));
        pnlLeftBottom.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        btnSales.setBackground(new java.awt.Color(51, 255, 204));
        btnSales.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSales.setText("BÁN HÀNG");
        btnSales.setPreferredSize(new java.awt.Dimension(90, 60));
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });
        pnlLeftBottom.add(btnSales);

        btnHistory.setBackground(new java.awt.Color(255, 204, 153));
        btnHistory.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnHistory.setText("LỊCH SỬ");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        pnlLeftBottom.add(btnHistory);

        btnChangePassword.setBackground(new java.awt.Color(255, 204, 0));
        btnChangePassword.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnChangePassword.setText("ĐỔI MẬT KHẨU");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        pnlLeftBottom.add(btnChangePassword);

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnExit.setText("KẾT THÚC");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlLeftBottom.add(btnExit);

        pnlLeft.add(pnlLeftBottom, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlLeft, java.awt.BorderLayout.LINE_START);

        pnlCenter.setLayout(new javax.swing.OverlayLayout(pnlCenter));

        pnlManager.setOpaque(false);
        pnlManager.setLayout(new java.awt.BorderLayout());

        pnlCenterBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlCenterBottom.setOpaque(false);
        pnlCenterBottom.setPreferredSize(new java.awt.Dimension(693, 150));
        pnlCenterBottom.setLayout(new java.awt.GridLayout(0, 3, 5, 5));

        btnDrinkMgr.setBackground(new java.awt.Color(255, 102, 0));
        btnDrinkMgr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnDrinkMgr.setText("ĐỒ UỐNG");
        btnDrinkMgr.setPreferredSize(new java.awt.Dimension(200, 60));
        btnDrinkMgr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDrinkMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkMgrActionPerformed(evt);
            }
        });
        pnlCenterBottom.add(btnDrinkMgr);

        btnCategoryMgr.setBackground(new java.awt.Color(204, 255, 0));
        btnCategoryMgr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCategoryMgr.setText("LOẠI ĐỒ UỐNG");
        btnCategoryMgr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCategoryMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryMgrActionPerformed(evt);
            }
        });
        pnlCenterBottom.add(btnCategoryMgr);

        btnCardMgr.setBackground(new java.awt.Color(255, 102, 0));
        btnCardMgr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCardMgr.setText("THẺ ĐỊNH DANH");
        btnCardMgr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCardMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardMgrActionPerformed(evt);
            }
        });
        pnlCenterBottom.add(btnCardMgr);

        btnBillMgr.setBackground(new java.awt.Color(255, 0, 102));
        btnBillMgr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnBillMgr.setText("PHIẾU BÁN HÀNG");
        btnBillMgr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBillMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillMgrActionPerformed(evt);
            }
        });
        pnlCenterBottom.add(btnBillMgr);

        btnUserMgr.setBackground(new java.awt.Color(51, 102, 255));
        btnUserMgr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnUserMgr.setText("NGƯỜI SỬ DỤNG");
        btnUserMgr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUserMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserMgrActionPerformed(evt);
            }
        });
        pnlCenterBottom.add(btnUserMgr);

        btnReportMgr.setBackground(new java.awt.Color(255, 51, 255));
        btnReportMgr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnReportMgr.setText("DOANH THU");
        btnReportMgr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportMgrActionPerformed(evt);
            }
        });
        pnlCenterBottom.add(btnReportMgr);

        pnlManager.add(pnlCenterBottom, java.awt.BorderLayout.PAGE_END);

        pnlCenter.add(pnlManager);

        pnlBackground.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/coffee-shop.jpg"))); // NOI18N
        pnlBackground.add(jLabel1);

        pnlCenter.add(pnlBackground);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        this.showChangePasswordJDialog(this);
        sendNotification("Đổi mật khẩu", "Bạn đang thay đổi mật khẩu tài khoản.");
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        this.showHistoryJDialog(this);
        sendNotification("Lịch sử giao dịch", "Đang xem lịch sử hóa đơn và giao dịch.");
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        // TODO add your handling code here:
        this.showSalesJDialog(this);
        sendNotification("Doanh thu", "Đang hiển thị báo cáo doanh thu.");
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.exit();
        sendNotification("Thoát ứng dụng", "Bạn đã thoát khỏi phần mềm quản lý.");
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDrinkMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkMgrActionPerformed
        // TODO add your handling code here:
        this.showDrinkManagerJDialog(this);
        sendNotification("Quản lý đồ uống", "Đang quản lý danh sách đồ uống trong quán.");
    }//GEN-LAST:event_btnDrinkMgrActionPerformed

    private void btnCategoryMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryMgrActionPerformed
        // TODO add your handling code here:
        this.showCategoryManagerJDialog(this);
         sendNotification("Quản lý danh mục", "Đang cập nhật và kiểm tra danh mục sản phẩm.");
    }//GEN-LAST:event_btnCategoryMgrActionPerformed

    private void btnCardMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardMgrActionPerformed
        // TODO add your handling code here:
        this.showCardManagerJDialog(this);
        sendNotification("Quản lý thẻ", "Đang thao tác với dữ liệu thẻ thành viên.");
    }//GEN-LAST:event_btnCardMgrActionPerformed

    private void btnBillMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillMgrActionPerformed
        this.showBillManagerJDialog(this);
        sendNotification("Quản lý hóa đơn", "Đang xem và cập nhật thông tin hóa đơn.");
                // TODO add your handling code here:

    }//GEN-LAST:event_btnBillMgrActionPerformed

    private void btnUserMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMgrActionPerformed
        // TODO add your handling code here:
        this.showUserManagerJDialog(this);
          sendNotification("Quản lý người dùng", "Đang điều phối tài khoản người dùng trong hệ thống.");
    }//GEN-LAST:event_btnUserMgrActionPerformed

    private void btnReportMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportMgrActionPerformed
        sendNotification("Quản lý báo cáo", "Đang xem báo cáo tổng hợp doanh thu và hoạt động.");
        this.showRevenueManagerJDialog(this);
    }//GEN-LAST:event_btnReportMgrActionPerformed

    private void lblPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhotoMouseClicked
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
        "Image files", "jpg", "jpeg", "png", "gif"));

    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();

        String photosFolder = "photos/";
        File dir = new File(photosFolder);
        if (!dir.exists()) dir.mkdirs();

        String photoPath = photosFolder + selectedFile.getName();

        try {
            // Copy file ảnh vào thư mục photos, ghi đè nếu trùng tên
            Path targetPath = Paths.get(photoPath);
            Files.copy(selectedFile.toPath(), targetPath, StandardCopyOption.REPLACE_EXISTING);

            // Cập nhật ảnh đại diện lên lblPhoto
            XIcon.setIcon(lblPhoto, photoPath);

            // Cập nhật ảnh đại diện trong bộ nhớ
            XAuth.user.setPhoto(selectedFile.getName());

            // Cập nhật ảnh đại diện trong database qua DAO
            boolean updateSuccess = UserDAOImpl.getInstance()
                .updatePhoto(XAuth.user.getUsername(), selectedFile.getName());

            if (updateSuccess) {
                JOptionPane.showMessageDialog(this, "Đổi ảnh đại diện thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật ảnh đại diện vào database thất bại!");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu ảnh đại diện: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_lblPhotoMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    
    // 1. Tạo một thể hiện của EditJDialog
    // 'this' ở đây là Frame hoặc Dialog chứa nút btnEdit
    EditJDialog editDialog = new EditJDialog(this, true); 
    
    // 2. Hiển thị EditJDialog
    editDialog.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
// ✅ Kiểm tra kết nối Internet
    InternetChecker internetChecker = new InternetChecker(() -> {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Không có kết nối Internet. Ứng dụng sẽ thoát.",
            "Mất kết nối",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    });
    internetChecker.start();

    // ✅ Kiểm tra hệ điều hành có phải Windows 10 trở lên
    boolean isWindows10OrHigher = false;
    String osName = System.getProperty("os.name");
    String osVersion = System.getProperty("os.version");

    if (osName.toLowerCase().contains("windows")) {
        try {
            String[] parts = osVersion.split("\\.");
            int major = Integer.parseInt(parts[0]);
            isWindows10OrHigher = major >= 10;
        } catch (Exception e) {
            isWindows10OrHigher = false;
        }
    }

    if (!isWindows10OrHigher) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Ứng dụng chỉ hỗ trợ trên Windows 10 trở lên.\nHệ điều hành hiện tại: " + osName + " " + osVersion,
            "Không hỗ trợ hệ điều hành",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }

    // ✅ Kiểm tra Wi-Fi 5 và TPM ≥ 1.2
    boolean wifi5 = false;
    boolean tpm1_2_or_higher = false;

    try {
        // Kiểm tra Wi-Fi 5
        Process wifiProcess = Runtime.getRuntime().exec("netsh wlan show drivers");
        java.util.Scanner wifiScanner = new java.util.Scanner(wifiProcess.getInputStream()).useDelimiter("\\A");
        String wifiOutput = wifiScanner.hasNext() ? wifiScanner.next() : "";
        wifiScanner.close();
        wifi5 = wifiOutput.contains("802.11ac");

        // Kiểm tra TPM ≥ 1.2
        Process tpmProcess = Runtime.getRuntime().exec("wmic /namespace:\\\\root\\CIMV2\\Security\\MicrosoftTpm path Win32_Tpm get SpecVersion");
        java.util.Scanner tpmScanner = new java.util.Scanner(tpmProcess.getInputStream()).useDelimiter("\\A");
        String tpmOutput = tpmScanner.hasNext() ? tpmScanner.next() : "";
        tpmScanner.close();
        tpm1_2_or_higher = tpmOutput.contains("1.2") || tpmOutput.contains("2.0");

    } catch (Exception e) {
        wifi5 = false;
        tpm1_2_or_higher = true;
    }

    // ✅ Kiểm tra CPU phải từ thế hệ thứ 6 trở lên
    boolean cpuGen6OrHigher = false;
    try {
        Process cpuProcess = Runtime.getRuntime().exec("wmic cpu get Name");
        java.util.Scanner cpuScanner = new java.util.Scanner(cpuProcess.getInputStream()).useDelimiter("\\A");
        String cpuOutput = cpuScanner.hasNext() ? cpuScanner.next() : "";
        cpuScanner.close();

        // Ví dụ tên CPU: "Intel(R) Core(TM) i5-6200U @ 2.30GHz"
        java.util.regex.Matcher matcher = java.util.regex.Pattern.compile("i[3579]-([6-9]\\d{2,}|[1-9]\\d{3,})").matcher(cpuOutput);
        if (matcher.find()) {
            cpuGen6OrHigher = true;
        }
    } catch (Exception e) {
        cpuGen6OrHigher = false;
    }

    if (!cpuGen6OrHigher) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Máy của bạn có CPU dưới thế hệ thứ 6.\nYêu cầu CPU từ thế hệ 6 trở lên để sử dụng ứng dụng.",
            "CPU không đạt yêu cầu",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }

    // ✅ Kiểm tra số lõi xử lý (cores/logical processors)
    int coreCount = Runtime.getRuntime().availableProcessors(); // logical cores

    if (coreCount < 2) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Máy tính của bạn chỉ có " + coreCount + " lõi xử lý.\nYêu cầu ít nhất 2 lõi để sử dụng ứng dụng.",
            "Không đủ lõi CPU",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }

    // ✅ Ràng buộc logic: Không có Wi-Fi 5 và lại có TPM => bị từ chối
    if (!wifi5 && tpm1_2_or_higher) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Máy không hỗ trợ Wi-Fi 5 mà lại có TPM 1.2 trở lên.\nKhông được phép sử dụng ứng dụng này.",
            "Từ chối truy cập",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }
    }//GEN-LAST:event_formWindowOpened

    private void btnTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeActionPerformed
        YearsUsersManagerJDialog dialog = new YearsUsersManagerJDialog(this, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btnTimeActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        try {
            // Tạo một thể hiện mới của QuanLiKhachHangJDialog
            // 'this' ở đây tham chiếu đến JFrame/JDialog hiện tại đang chứa nút này,
            // dùng làm cha cho JDialog mới để nó có thể hiển thị modal (nếu cần)
            QuanLiKhachHangJDialog khDialog = new QuanLiKhachHangJDialog(this, true); // true để dialog là modal
            khDialog.setVisible(true); // Hiển thị dialog
        } catch (Exception e) {
            // Xử lý lỗi nếu có vấn đề khi khởi tạo hoặc hiển thị dialog
            JOptionPane.showMessageDialog(this, "Lỗi khi mở cửa sổ quản lý khách hàng: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // In stack trace để debug
        }
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnQuanLiDoAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiDoAnActionPerformed
        FoodManagerJDialog foodManagerDialog = new FoodManagerJDialog(this, true); // 'this' refers to the parent frame, 'true' makes it modal

    // Set the dialog to be visible
    foodManagerDialog.setVisible(true);
    }//GEN-LAST:event_btnQuanLiDoAnActionPerformed

    private void btnKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenMaiActionPerformed
        KhuyenMaiJDialog khuyenMaiJDialog = new KhuyenMaiJDialog(this, true);
        khuyenMaiJDialog.setVisible(true);
    }//GEN-LAST:event_btnKhuyenMaiActionPerformed

    private void btnWifiManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWifiManagerActionPerformed
        WifiManagerJDialog wifiDialog = new WifiManagerJDialog(this, true); // this là JFrame cha
    wifiDialog.setLocationRelativeTo(this); // Căn giữa theo cửa sổ cha
    wifiDialog.setVisible(true); // Hiển thị cửa sổ
    }//GEN-LAST:event_btnWifiManagerActionPerformed
    // Kiểm tra version Java

private void sendNotification(String title, String message) {
    if (!SystemTray.isSupported()) {
        System.out.println("System tray not supported!");
        return;
    }

    SystemTray tray = SystemTray.getSystemTray();
    Image image = Toolkit.getDefaultToolkit().createImage("icon.png"); // Thay bằng icon phù hợp

    TrayIcon trayIcon = new TrayIcon(image, "App Notification");
    trayIcon.setImageAutoSize(true);
    trayIcon.setToolTip("Thông báo từ ứng dụng quản lý quán cafe");

    try {
        tray.add(trayIcon);
        trayIcon.displayMessage(title, message, TrayIcon.MessageType.INFO);
        tray.remove(trayIcon); // Loại bỏ để tránh trùng lặp
    } catch (AWTException e) {
        e.printStackTrace();
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolyCafeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillMgr;
    private javax.swing.JButton btnCardMgr;
    private javax.swing.JButton btnCategoryMgr;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDrinkMgr;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnKhuyenMai;
    private javax.swing.JButton btnQuanLiDoAn;
    private javax.swing.JButton btnReportMgr;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnTime;
    private javax.swing.JButton btnUserMgr;
    private javax.swing.JToggleButton btnWifiManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlCenterBottom;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlLeftBottom;
    private javax.swing.JPanel pnlLeftCenter;
    private javax.swing.JPanel pnlManager;
    // End of variables declaration//GEN-END:variables

@Override
public void init() {
    this.setIconImage(XIcon.getIcon("trump-small.png").getImage());
    this.setLocationRelativeTo(null);

    this.showWelcomeJDialog(this);
    this.showKetNoiWifiJDialog(this);
    this.showLoginJDialog(this);

    XIcon.setIcon(lblPhoto, "photos/" + XAuth.user.getPhoto());
    lblFullname.setText(XAuth.user.getFullname());

    if(!XAuth.user.isManager()){
        pnlCenter.remove(pnlManager);
    }
}


}