/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.ui1;

import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import poly.cafe.dao.impl.UserDAOImpl;
import poly.cafe.entity.User;

/**
 *
 * @author Hieu
 */
public class YearsUsersManagerJDialog extends javax.swing.JDialog {

    /**
     * Creates new form YearsUsersManagerJDialog
     */
    public YearsUsersManagerJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblYearsWorks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("QUẢN TRỊ SỐ NĂM QUẢN LÍ QUÁN CAFE (NẾU LÀ NĂM CUỐI THÌ SẼ KO ĐƯỢC TRUY CẬP NỮA)");

        tblYearsWorks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Tên đăng nhập", "Vai trò", "Số năm", "Ngày tạo", "Số năm đã sử dụng", "Số năm còn lại", "Ngày kết thúc", "Năm hiện tại là năm mấy", "Ngày đã sử dụng"
            }
        ));
        jScrollPane1.setViewportView(tblYearsWorks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel model = (DefaultTableModel) tblYearsWorks.getModel();
model.setRowCount(0);

List<User> list = UserDAOImpl.getInstance().findAll();
Date today = new Date();

for (User u : list) {
    if (!u.isManager()) continue;

    Date created = u.getCreatedDate();

    int yearsUsed = 0;
    int yearsLeft = 4;
    String createdStr = "Không rõ";
    String endedStr = "Không xác định";
    String currentYearStr = "Không rõ";
    long daysUsed = 0;

    if (created != null) {
        yearsUsed = getYearDifference(created, today);
        yearsLeft = 4 - yearsUsed;
        createdStr = formatDate(created);
        endedStr = formatDate(addYears(created, 4));
        currentYearStr = "Năm " + (yearsUsed + 1);
        daysUsed = getDayDifference(created, today); // <== Tính số ngày sử dụng
    }

    model.addRow(new Object[]{
        u.getUsername(),
        u.getFullname(),
        u.isManager() ? "Quản lí" : "Nhân viên",
        4,
        createdStr,
        yearsUsed,
        yearsLeft,
        endedStr,
        currentYearStr,
        daysUsed + " ngày" // <== Thêm dòng hiển thị số ngày
    });

    if (created != null && yearsLeft <= 0) {
        UserDAOImpl.getInstance().deleteById(u.getUsername());
    }
}




    }//GEN-LAST:event_formWindowOpened
    private int getYearDifference(Date from, Date to) {
    Calendar start = Calendar.getInstance();
    Calendar end = Calendar.getInstance();
    start.setTime(from);
    end.setTime(to);
    return end.get(Calendar.YEAR) - start.get(Calendar.YEAR);
}

private String formatDate(Date date) {
    return new java.text.SimpleDateFormat("dd/MM/yyyy").format(date);
}

private Date addYears(Date date, int years) {
    Calendar calendar = Calendar.getInstance();
    calendar.setTime(date);
    calendar.add(Calendar.YEAR, years);
    return calendar.getTime();
}
private long getDayDifference(Date startDate, Date endDate) {
    long diffInMillies = endDate.getTime() - startDate.getTime();
    return diffInMillies / (1000 * 60 * 60 * 24);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YearsUsersManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YearsUsersManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YearsUsersManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YearsUsersManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                YearsUsersManagerJDialog dialog = new YearsUsersManagerJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblYearsWorks;
    // End of variables declaration//GEN-END:variables
}
